// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjr_uUHEeRiWJoq3aNLVrZgMjcw6FhB8',
    appId: '1:432468585037:web:0081111156b0ceedd64a04',
    messagingSenderId: '432468585037',
    projectId: 'kitapbar-bb30d',
    authDomain: 'kitapbar-bb30d.firebaseapp.com',
    storageBucket: 'kitapbar-bb30d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9vZQ0YH5fZ4IBwA66paJIAW9dQ4SH3rI',
    appId: '1:432468585037:android:03c1cd5d28151df2d64a04',
    messagingSenderId: '432468585037',
    projectId: 'kitapbar-bb30d',
    storageBucket: 'kitapbar-bb30d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLNjEWSxZ9pJkEA9phKZcn0pkqkxqDfc',
    appId: '1:432468585037:ios:a177e1d78fe4523dd64a04',
    messagingSenderId: '432468585037',
    projectId: 'kitapbar-bb30d',
    storageBucket: 'kitapbar-bb30d.appspot.com',
    iosBundleId: 'com.example.flutterKitapBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLNjEWSxZ9pJkEA9phKZcn0pkqkxqDfc',
    appId: '1:432468585037:ios:ff3d03233c12f3bed64a04',
    messagingSenderId: '432468585037',
    projectId: 'kitapbar-bb30d',
    storageBucket: 'kitapbar-bb30d.appspot.com',
    iosBundleId: 'com.example.flutterKitapBar.RunnerTests',
  );
}
